import Head from "next/head";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title></title>
        <meta name="description" content="Generated by create next app" />
        <meta name="keywords" content="blog,blog spot" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <h1>Hunting Coders</h1>
        <hr className={styles.lines} />
        <h2>Popular Blogs</h2>
        <div className={styles.grid}>
          <a
            href="#"
            className={styles.card}
            target="_blank"
            rel="noopener noreferrer"
          >
            <h2 className={inter.className}>
              Javascript Libraies in 2023 <span>-&gt;</span>
            </h2>
            <p className={inter.className}>
              List of amazing javascript libraies, let explore&nbsp; together in
              2023
            </p>
          </a>

          <a
            href="#"
            className={styles.card}
            target="_blank"
            rel="noopener noreferrer"
          >
            <h2 className={inter.className}>
              Javascript Libraies in 2023 <span>-&gt;</span>
            </h2>
            <p className={inter.className}>
              List of amazing javascript libraies, let explore&nbsp; together in
              2023
            </p>
          </a>

          <a
            href="#"
            className={styles.card}
            target="_blank"
            rel="noopener noreferrer"
          >
            <h2 className={inter.className}>
              Javascript Libraies in 2023 <span>-&gt;</span>
            </h2>
            <p className={inter.className}>
              List of amazing javascript libraies, let explore&nbsp; together in
              2023
            </p>
          </a>

          <a
            href="#"
            className={styles.card}
            target="_blank"
            rel="noopener noreferrer"
          >
            <h2 className={inter.className}>
              Javascript Libraies in 2023 <span>-&gt;</span>
            </h2>
            <p className={inter.className}>
              List of amazing javascript libraies, let explore&nbsp; together in
              2023
            </p>
          </a>
        </div>
      </main>
    </>
  );
}
