import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";
import Script from "next/script";
import Link from "next/link";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Next JS</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="keywords" content="blog,blog spot" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Script id="script1" src="/seo.js" strategy="lazyOnload">
        {console.log("custom script inner part")}
      </Script>
      <main className={styles.main}>
        <nav>
          <ul>
            <li>
              <Link href='/'>Home</Link>
            </li>
            <li>
              <Link href='/about'>About</Link>
            </li>
            <li>
              <Link href='/contact'>Contact</Link>
            </li>
            <li>
              <Link href='/blog'>Blogs</Link>
            </li>
          </ul>
        </nav>

        <h1>Hunting Coders</h1>
        <hr className={styles.lines} />
        <h2>Popular Blogs</h2>
        <div className={styles.grid}>

          <a
            href="#"
            className={styles.card}
            target="_blank"
            rel="noopener noreferrer"
          >
            <h2 className={inter.className}>
              Javascript Libraies in 2023 <span>-&gt;</span>
            </h2>
            <p className={inter.className}>
              List of amazing javascript libraies, let explore&nbsp; together  in 2023
            </p>
          </a>

          <a
            href="#"
            className={styles.card}
            target="_blank"
            rel="noopener noreferrer"
          >
            <h2 className={inter.className}>
              Javascript Libraies in 2023 <span>-&gt;</span>
            </h2>
            <p className={inter.className}>
              List of amazing javascript libraies, let explore&nbsp; together  in 2023
            </p>
          </a>

          <a
            href="#"
            className={styles.card}
            target="_blank"
            rel="noopener noreferrer"
          >
            <h2 className={inter.className}>
              Javascript Libraies in 2023 <span>-&gt;</span>
            </h2>
            <p className={inter.className}>
              List of amazing javascript libraies, let explore&nbsp; together  in 2023
            </p>
          </a>

          <a
            href="#"
            className={styles.card}
            target="_blank"
            rel="noopener noreferrer"
          >
            <h2 className={inter.className}>
              Javascript Libraies in 2023 <span>-&gt;</span>
            </h2>
            <p className={inter.className}>
              List of amazing javascript libraies, let explore&nbsp; together  in 2023
            </p>
          </a>


        </div>
      </main>
    </>
  );
}
